# Generated by Django 3.0 on 2020-07-02 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='branches',
            new_name='branchesd',
        ),
    ]
